on:
  push:
    branches:
      - main
    paths:
      - update.mjs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - run: pnpm run update
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update'
          file_pattern: README.md
